/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AudioApi,
  CatalogApi,
  ComputerVisionApi,
  ContributorsApi,
  CustomMusicApi,
  EditorialImagesApi,
  EditorialVideoApi,
  ImagesApi,
  OauthApi,
  SoundEffectsApi,
  TestApi,
  UsersApi,
  VideosApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { ShutterstockCustom } from "./client-custom";

export class Shutterstock extends ShutterstockCustom {
  readonly audio: AudioApi;
  readonly catalog: CatalogApi;
  readonly computerVision: ComputerVisionApi;
  readonly contributors: ContributorsApi;
  readonly customMusic: CustomMusicApi;
  readonly editorialImages: EditorialImagesApi;
  readonly editorialVideo: EditorialVideoApi;
  readonly images: ImagesApi;
  readonly oauth: OauthApi;
  readonly soundEffects: SoundEffectsApi;
  readonly test: TestApi;
  readonly users: UsersApi;
  readonly videos: VideosApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.audio = new AudioApi(configuration);
    this.catalog = new CatalogApi(configuration);
    this.computerVision = new ComputerVisionApi(configuration);
    this.contributors = new ContributorsApi(configuration);
    this.customMusic = new CustomMusicApi(configuration);
    this.editorialImages = new EditorialImagesApi(configuration);
    this.editorialVideo = new EditorialVideoApi(configuration);
    this.images = new ImagesApi(configuration);
    this.oauth = new OauthApi(configuration);
    this.soundEffects = new SoundEffectsApi(configuration);
    this.test = new TestApi(configuration);
    this.users = new UsersApi(configuration);
    this.videos = new VideosApi(configuration);
  }

}
