/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Access token details that are currently associated with this user
 * @export
 * @interface AccessTokenDetails
 */
export interface AccessTokenDetails {
    /**
     * Client ID that is associated with the user
     * @type {string}
     * @memberof AccessTokenDetails
     */
    'client_id'?: string;
    /**
     * Contributor ID that is associated with the user
     * @type {string}
     * @memberof AccessTokenDetails
     */
    'contributor_id'?: string;
    /**
     * Customer ID that is associated with the user
     * @type {string}
     * @memberof AccessTokenDetails
     */
    'customer_id'?: string;
    /**
     * Number of seconds until the access token expires; no expiration if this value is null
     * @type {number}
     * @memberof AccessTokenDetails
     */
    'expires_in'?: number;
    /**
     * Organization ID that is associated with the user
     * @type {string}
     * @memberof AccessTokenDetails
     */
    'organization_id'?: string;
    /**
     * Type of access token
     * @type {string}
     * @memberof AccessTokenDetails
     */
    'realm'?: AccessTokenDetailsRealmEnum;
    /**
     * Scopes that this access token provides when used as authentication
     * @type {Array<string>}
     * @memberof AccessTokenDetails
     */
    'scopes'?: Array<string>;
    /**
     * User ID that is associated with the user
     * @type {string}
     * @memberof AccessTokenDetails
     */
    'user_id'?: string;
    /**
     * User name that is associated with the user
     * @type {string}
     * @memberof AccessTokenDetails
     */
    'username'?: string;
}

type AccessTokenDetailsRealmEnum = 'customer' | 'contributor'


