/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Album metadata
 * @export
 * @interface Album
 */
export interface Album {
    /**
     * The album title
     * @type {string}
     * @memberof Album
     */
    'title': string;
    /**
     * The album ID
     * @type {string}
     * @memberof Album
     */
    'id': string;
}

