/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AudioAssetDetails } from './audio-asset-details';
import { ShortsLoopsStems } from './shorts-loops-stems';

/**
 * Files that are available as part of an audio asset
 * @export
 * @interface AudioAssets
 */
export interface AudioAssets {
    /**
     * 
     * @type {AudioAssetDetails}
     * @memberof AudioAssets
     */
    'album_art'?: AudioAssetDetails;
    /**
     * 
     * @type {AudioAssetDetails}
     * @memberof AudioAssets
     */
    'clean_audio'?: AudioAssetDetails;
    /**
     * 
     * @type {AudioAssetDetails}
     * @memberof AudioAssets
     */
    'original_audio'?: AudioAssetDetails;
    /**
     * 
     * @type {AudioAssetDetails}
     * @memberof AudioAssets
     */
    'preview_mp3'?: AudioAssetDetails;
    /**
     * 
     * @type {AudioAssetDetails}
     * @memberof AudioAssets
     */
    'preview_ogg'?: AudioAssetDetails;
    /**
     * 
     * @type {ShortsLoopsStems}
     * @memberof AudioAssets
     */
    'shorts_loops_stems'?: ShortsLoopsStems;
    /**
     * 
     * @type {AudioAssetDetails}
     * @memberof AudioAssets
     */
    'waveform'?: AudioAssetDetails;
}

