/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AudioRenderTimelineSpan } from './audio-render-timeline-span';

/**
 * A timeline object that represents either a request for music to be created or an entire music composition
 * @export
 * @interface AudioRenderTimeline
 */
export interface AudioRenderTimeline {
    /**
     * A span object that represents the beginning of a period of absolute time
     * @type {Array<AudioRenderTimelineSpan>}
     * @memberof AudioRenderTimeline
     */
    'spans'?: Array<AudioRenderTimelineSpan>;
}

