/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AudioRenderTimelineSpanRegionEndType } from './audio-render-timeline-span-region-end-type';
import { AudioRenderTimelineSpanRegionKey } from './audio-render-timeline-span-region-key';

/**
 * A period of music or silence, measured in beats
 * @export
 * @interface AudioRenderTimelineSpanRegion
 */
export interface AudioRenderTimelineSpanRegion {
    /**
     * The beat, relative to the span, at which the region object\'s music begins
     * @type {number}
     * @memberof AudioRenderTimelineSpanRegion
     */
    'beat': number;
    /**
     * The descriptor ID needed to compose the music
     * @type {string}
     * @memberof AudioRenderTimelineSpanRegion
     */
    'descriptor': string;
    /**
     * 
     * @type {AudioRenderTimelineSpanRegionEndType}
     * @memberof AudioRenderTimelineSpanRegion
     */
    'end_type'?: AudioRenderTimelineSpanRegionEndType;
    /**
     * An identifier which must be unique within the parent span
     * @type {number}
     * @memberof AudioRenderTimelineSpanRegion
     */
    'id': number;
    /**
     * 
     * @type {AudioRenderTimelineSpanRegionKey}
     * @memberof AudioRenderTimelineSpanRegion
     */
    'key'?: AudioRenderTimelineSpanRegionKey;
    /**
     * The type of region
     * @type {string}
     * @memberof AudioRenderTimelineSpanRegion
     */
    'region': AudioRenderTimelineSpanRegionRegionEnum;
}

type AudioRenderTimelineSpanRegionRegionEnum = 'music' | 'silence'


