/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AudioRenderTimelineSpanInstrumentGroupStatus } from './audio-render-timeline-span-instrument-group-status';

/**
 * An instrument and the status objects that specify when that instrument plays
 * @export
 * @interface AudioRenderTimelineSpanInstrumentGroup
 */
export interface AudioRenderTimelineSpanInstrumentGroup {
    /**
     * The instrument ID
     * @type {string}
     * @memberof AudioRenderTimelineSpanInstrumentGroup
     */
    'instrument_group': string;
    /**
     * An array of status objects
     * @type {Array<AudioRenderTimelineSpanInstrumentGroupStatus>}
     * @memberof AudioRenderTimelineSpanInstrumentGroup
     */
    'statuses'?: Array<AudioRenderTimelineSpanInstrumentGroupStatus>;
}

