/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A high-level description of how a region ends
 * @export
 * @interface AudioRenderTimelineSpanRegionEndType
 */
export interface AudioRenderTimelineSpanRegionEndType {
    /**
     * The beat, relative to the start of the active region, at which the end_type begins; in other words, the ending starts on this beat of the region
     * @type {number}
     * @memberof AudioRenderTimelineSpanRegionEndType
     */
    'beat': number;
    /**
     * The type of event
     * @type {string}
     * @memberof AudioRenderTimelineSpanRegionEndType
     */
    'event': AudioRenderTimelineSpanRegionEndTypeEventEnum;
    /**
     * The specific action to perform; if the event type is \"ending\" then this must be \"ringout\" and if event type is \"transition\" this must be \"cut\"
     * @type {string}
     * @memberof AudioRenderTimelineSpanRegionEndType
     */
    'type': AudioRenderTimelineSpanRegionEndTypeTypeEnum;
}

type AudioRenderTimelineSpanRegionEndTypeEventEnum = 'ending' | 'transition'
type AudioRenderTimelineSpanRegionEndTypeTypeEnum = 'ringout' | 'cut'


