/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Files associated with the render
 * @export
 * @interface AudioRendersFilesList
 */
export interface AudioRendersFilesList {
    /**
     * The bit depth of the audio files in bits/sample
     * @type {number}
     * @memberof AudioRendersFilesList
     */
    'bits_sample': number;
    /**
     * The content-type of the file
     * @type {string}
     * @memberof AudioRendersFilesList
     */
    'content_type': string;
    /**
     * The internet-accessible URL from which the file can be downloaded. Any redirects encountered when using this URL must be followed
     * @type {string}
     * @memberof AudioRendersFilesList
     */
    'download_url': string;
    /**
     * The user-specified file name suggestion from the render request; this file name becomes the filename property of the Content-Disposition header when the user downloads the rendered audio file
     * @type {string}
     * @memberof AudioRendersFilesList
     */
    'filename': string;
    /**
     * The Sample rate of the audio files in Hertz (Hz)
     * @type {number}
     * @memberof AudioRendersFilesList
     */
    'frequency_hz': number;
    /**
     * The data rate of the audio files in kilobits/second
     * @type {number}
     * @memberof AudioRendersFilesList
     */
    'kbits_second': number;
    /**
     * Size of the file in bytes
     * @type {number}
     * @memberof AudioRendersFilesList
     */
    'size_bytes': number;
    /**
     * An array of track names included in the file
     * @type {Array<string>}
     * @memberof AudioRendersFilesList
     */
    'tracks': Array<string>;
}

