/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The status of an instrument at a specific beat
 * @export
 * @interface AudioRenderTimelineSpanInstrumentGroupStatus
 */
export interface AudioRenderTimelineSpanInstrumentGroupStatus {
    /**
     * The beat, relative to the span, at which the status begins
     * @type {number}
     * @memberof AudioRenderTimelineSpanInstrumentGroupStatus
     */
    'beat': number;
    /**
     * Whether the instrument is playing or not
     * @type {string}
     * @memberof AudioRenderTimelineSpanInstrumentGroupStatus
     */
    'status': AudioRenderTimelineSpanInstrumentGroupStatusStatusEnum;
}

type AudioRenderTimelineSpanInstrumentGroupStatusStatusEnum = 'active' | 'inactive'


