/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Audio License URL object
 * @export
 * @interface AudioUrl
 */
export interface AudioUrl {
    /**
     * URL that can be used to download the .zip file containing shorts, loops, and stems
     * @type {string}
     * @memberof AudioUrl
     */
    'shorts_loops_stems'?: string;
    /**
     * URL that can be used to download the unwatermarked, licensed asset
     * @type {string}
     * @memberof AudioUrl
     */
    'url': string;
}

