/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A band that can be used to generate music
 * @export
 * @interface Bands
 */
export interface Bands {
    /**
     * The ID of the band
     * @type {string}
     * @memberof Bands
     */
    'id'?: string;
    /**
     * The name of the band
     * @type {string}
     * @memberof Bands
     */
    'name'?: string;
}

