/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CatalogCollectionItemAsset } from './catalog-collection-item-asset';

/**
 * Metadata about an item that is part of a collection
 * @export
 * @interface CatalogCollectionItem
 */
export interface CatalogCollectionItem {
    /**
     * 
     * @type {CatalogCollectionItemAsset}
     * @memberof CatalogCollectionItem
     */
    'asset': CatalogCollectionItemAsset;
    /**
     * The collection IDs that this asset belongs to
     * @type {Array<string>}
     * @memberof CatalogCollectionItem
     */
    'collection_ids'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CatalogCollectionItem
     */
    'created_time': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogCollectionItem
     */
    'id': string;
}

