/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CatalogCollectionItem } from './catalog-collection-item';

/**
 * List of catalog collection items
 * @export
 * @interface CatalogCollectionItemDataList
 */
export interface CatalogCollectionItemDataList {
    /**
     * List of catalog collection items
     * @type {Array<CatalogCollectionItem>}
     * @memberof CatalogCollectionItemDataList
     */
    'data': Array<CatalogCollectionItem>;
    /**
     * 
     * @type {number}
     * @memberof CatalogCollectionItemDataList
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof CatalogCollectionItemDataList
     */
    'per_page': number;
    /**
     * 
     * @type {number}
     * @memberof CatalogCollectionItemDataList
     */
    'total_count': number;
}

