/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CatalogCollectionItem } from './catalog-collection-item';
import { CatalogCollectionRoleAssignments } from './catalog-collection-role-assignments';

/**
 * Catalog collection
 * @export
 * @interface CatalogCollection
 */
export interface CatalogCollection {
    /**
     * 
     * @type {CatalogCollectionItem}
     * @memberof CatalogCollection
     */
    'cover_asset'?: CatalogCollectionItem;
    /**
     * 
     * @type {string}
     * @memberof CatalogCollection
     */
    'created_time': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogCollection
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogCollection
     */
    'name': string;
    /**
     * 
     * @type {CatalogCollectionRoleAssignments}
     * @memberof CatalogCollection
     */
    'role_assignments': CatalogCollectionRoleAssignments;
    /**
     * 
     * @type {number}
     * @memberof CatalogCollection
     */
    'total_item_count': number;
    /**
     * 
     * @type {string}
     * @memberof CatalogCollection
     */
    'updated_time': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogCollection
     */
    'visibility': CatalogCollectionVisibilityEnum;
}

type CatalogCollectionVisibilityEnum = 'private' | 'public'


