/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CatalogCollection } from './catalog-collection';

/**
 * List of catalog collections
 * @export
 * @interface CatalogCollectionDataList
 */
export interface CatalogCollectionDataList {
    /**
     * List of catalog collections
     * @type {Array<CatalogCollection>}
     * @memberof CatalogCollectionDataList
     */
    'data': Array<CatalogCollection>;
    /**
     * 
     * @type {number}
     * @memberof CatalogCollectionDataList
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof CatalogCollectionDataList
     */
    'per_page': number;
    /**
     * 
     * @type {number}
     * @memberof CatalogCollectionDataList
     */
    'total_count': number;
}

