/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A user that has access to a catalog collection
 * @export
 * @interface CatalogCollectionRole
 */
export interface CatalogCollectionRole {
    /**
     * 
     * @type {string}
     * @memberof CatalogCollectionRole
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogCollectionRole
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CatalogCollectionRole
     */
    'type': CatalogCollectionRoleTypeEnum;
}

type CatalogCollectionRoleTypeEnum = 'USER'


