/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Category } from './category';

/**
 * List of categories that images can belong to
 * @export
 * @interface CategoryDataList
 */
export interface CategoryDataList {
    /**
     * Categories
     * @type {Array<Category>}
     * @memberof CategoryDataList
     */
    'data'?: Array<Category>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof CategoryDataList
     */
    'errors'?: Array<Error>;
    /**
     * Server-generated message, if any
     * @type {string}
     * @memberof CategoryDataList
     */
    'message'?: string;
    /**
     * The current page of results
     * @type {number}
     * @memberof CategoryDataList
     */
    'page'?: number;
    /**
     * The number of results per page
     * @type {number}
     * @memberof CategoryDataList
     */
    'per_page'?: number;
    /**
     * The total number of results across all pages
     * @type {number}
     * @memberof CategoryDataList
     */
    'total_count'?: number;
}

