/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Category information
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * Category ID
     * @type {string}
     * @memberof Category
     */
    'id'?: string;
    /**
     * Category name
     * @type {string}
     * @memberof Category
     */
    'name'?: string;
}

