/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CollectionItem } from './collection-item';

/**
 * Metadata about a collection of assets
 * @export
 * @interface Collection
 */
export interface Collection {
    /**
     * 
     * @type {CollectionItem}
     * @memberof Collection
     */
    'cover_item'?: CollectionItem;
    /**
     * When the collection was created
     * @type {string}
     * @memberof Collection
     */
    'created_time'?: string;
    /**
     * The collection ID
     * @type {string}
     * @memberof Collection
     */
    'id': string;
    /**
     * The last time this collection\'s items were updated
     * @type {string}
     * @memberof Collection
     */
    'items_updated_time'?: string;
    /**
     * The name of the collection
     * @type {string}
     * @memberof Collection
     */
    'name': string;
    /**
     * A code that can be used to share the collection (optional)
     * @type {string}
     * @memberof Collection
     */
    'share_code'?: string;
    /**
     * The browser URL that can be used to share the collection (optional)
     * @type {string}
     * @memberof Collection
     */
    'share_url'?: string;
    /**
     * The number of items in the collection
     * @type {number}
     * @memberof Collection
     */
    'total_item_count': number;
    /**
     * The last time the collection was update (other than changes to the items in it)
     * @type {string}
     * @memberof Collection
     */
    'updated_time'?: string;
}

