/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Collection } from './collection';

/**
 * List of collections
 * @export
 * @interface CollectionDataList
 */
export interface CollectionDataList {
    /**
     * Collections
     * @type {Array<Collection>}
     * @memberof CollectionDataList
     */
    'data'?: Array<Collection>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof CollectionDataList
     */
    'errors'?: Array<Error>;
    /**
     * Server-generated message, if any
     * @type {string}
     * @memberof CollectionDataList
     */
    'message'?: string;
    /**
     * The current page of results
     * @type {number}
     * @memberof CollectionDataList
     */
    'page'?: number;
    /**
     * The number of results per page
     * @type {number}
     * @memberof CollectionDataList
     */
    'per_page'?: number;
    /**
     * The total number of results across all pages
     * @type {number}
     * @memberof CollectionDataList
     */
    'total_count'?: number;
}

