/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Contributor profile social media links
 * @export
 * @interface ContributorProfileSocialMedia
 */
export interface ContributorProfileSocialMedia {
    /**
     * Facebook link for contributor
     * @type {string}
     * @memberof ContributorProfileSocialMedia
     */
    'facebook'?: string;
    /**
     * Google+ link for contributor
     * @type {string}
     * @memberof ContributorProfileSocialMedia
     */
    'google_plus'?: string;
    /**
     * LinkedIn link for contributor
     * @type {string}
     * @memberof ContributorProfileSocialMedia
     */
    'linkedin'?: string;
    /**
     * Pinterest page for contributor
     * @type {string}
     * @memberof ContributorProfileSocialMedia
     */
    'pinterest'?: string;
    /**
     * Tumblr link for contributor
     * @type {string}
     * @memberof ContributorProfileSocialMedia
     */
    'tumblr'?: string;
    /**
     * Twitter link for contributor
     * @type {string}
     * @memberof ContributorProfileSocialMedia
     */
    'twitter'?: string;
}

