/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContributorProfile } from './contributor-profile';

/**
 * List of contributor profiles
 * @export
 * @interface ContributorProfileDataList
 */
export interface ContributorProfileDataList {
    /**
     * Conributor profiles
     * @type {Array<ContributorProfile>}
     * @memberof ContributorProfileDataList
     */
    'data'?: Array<ContributorProfile>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof ContributorProfileDataList
     */
    'errors'?: Array<Error>;
    /**
     * Error message
     * @type {string}
     * @memberof ContributorProfileDataList
     */
    'message'?: string;
    /**
     * Page of response
     * @type {number}
     * @memberof ContributorProfileDataList
     */
    'page'?: number;
    /**
     * Number of contributors per page
     * @type {number}
     * @memberof ContributorProfileDataList
     */
    'per_page'?: number;
    /**
     * Total count of contributors for this request
     * @type {number}
     * @memberof ContributorProfileDataList
     */
    'total_count'?: number;
}

