/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateAudioRender } from './create-audio-render';

/**
 * Render request data
 * @export
 * @interface CreateAudioRendersRequest
 */
export interface CreateAudioRendersRequest {
    /**
     * Parameters to create computer audio renders
     * @type {Array<CreateAudioRender>}
     * @memberof CreateAudioRendersRequest
     */
    'audio_renders': Array<CreateAudioRender>;
}

