/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DownloadHistory } from './download-history';

/**
 * List of download events
 * @export
 * @interface DownloadHistoryDataList
 */
export interface DownloadHistoryDataList {
    /**
     * Download events
     * @type {Array<DownloadHistory>}
     * @memberof DownloadHistoryDataList
     */
    'data'?: Array<DownloadHistory>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof DownloadHistoryDataList
     */
    'errors'?: Array<Error>;
    /**
     * Server-generated message, if any
     * @type {string}
     * @memberof DownloadHistoryDataList
     */
    'message'?: string;
    /**
     * The current page of results
     * @type {number}
     * @memberof DownloadHistoryDataList
     */
    'page'?: number;
    /**
     * The number of results per page
     * @type {number}
     * @memberof DownloadHistoryDataList
     */
    'per_page'?: number;
    /**
     * The total number of results across all pages
     * @type {number}
     * @memberof DownloadHistoryDataList
     */
    'total_count'?: number;
}

