/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DownloadHistoryMediaDetails } from './download-history-media-details';
import { DownloadHistoryRevshareDetails } from './download-history-revshare-details';
import { DownloadHistoryUserDetails } from './download-history-user-details';

/**
 * Information about a downloaded media item. Applicable for all media types, only one of \'audio\', \'image\' or \'video\' will be in a single DownloadHistory object
 * @export
 * @interface DownloadHistory
 */
export interface DownloadHistory {
    /**
     * 
     * @type {DownloadHistoryMediaDetails}
     * @memberof DownloadHistory
     */
    'audio'?: DownloadHistoryMediaDetails;
    /**
     * Date the media was downloaded the first time
     * @type {string}
     * @memberof DownloadHistory
     */
    'download_time': string;
    /**
     * ID of the download
     * @type {string}
     * @memberof DownloadHistory
     */
    'id': string;
    /**
     * 
     * @type {DownloadHistoryMediaDetails}
     * @memberof DownloadHistory
     */
    'image'?: DownloadHistoryMediaDetails;
    /**
     * Specifies if the media is downloadable via its respective downloads endpoint
     * @type {boolean}
     * @memberof DownloadHistory
     */
    'is_downloadable'?: boolean;
    /**
     * The name of the license of this download
     * @type {string}
     * @memberof DownloadHistory
     */
    'license': string;
    /**
     * The metadata that was passed in the original licensing request
     * @type {object}
     * @memberof DownloadHistory
     */
    'metadata'?: object;
    /**
     * 
     * @type {DownloadHistoryRevshareDetails}
     * @memberof DownloadHistory
     */
    'revshare'?: DownloadHistoryRevshareDetails;
    /**
     * ID of the subscription used to perform this download
     * @type {string}
     * @memberof DownloadHistory
     */
    'subscription_id'?: string;
    /**
     * 
     * @type {DownloadHistoryUserDetails}
     * @memberof DownloadHistory
     */
    'user'?: DownloadHistoryUserDetails;
    /**
     * 
     * @type {DownloadHistoryMediaDetails}
     * @memberof DownloadHistory
     */
    'video'?: DownloadHistoryMediaDetails;
}

