/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Pricing information for revenue-sharing transactions
 * @export
 * @interface DownloadHistoryRevshareDetails
 */
export interface DownloadHistoryRevshareDetails {
    /**
     * The amount charged for the license
     * @type {string}
     * @memberof DownloadHistoryRevshareDetails
     */
    'purchase_amount': string;
    /**
     * The currency the amount was charged in
     * @type {string}
     * @memberof DownloadHistoryRevshareDetails
     */
    'purchase_currency': string;
}

