/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Name of an editorial category
 * @export
 * @interface EditorialCategory
 */
export interface EditorialCategory {
    /**
     * 
     * @type {string}
     * @memberof EditorialCategory
     */
    'name'?: string;
}

