/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EditorialContent } from './editorial-content';

/**
 * List of editorial items
 * @export
 * @interface EditorialImageContentDataList
 */
export interface EditorialImageContentDataList {
    /**
     * Editorial items
     * @type {Array<EditorialContent>}
     * @memberof EditorialImageContentDataList
     */
    'data'?: Array<EditorialContent>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof EditorialImageContentDataList
     */
    'errors'?: Array<Error>;
    /**
     * Optional error message
     * @type {string}
     * @memberof EditorialImageContentDataList
     */
    'message'?: string;
    /**
     * Current page of the response
     * @type {number}
     * @memberof EditorialImageContentDataList
     */
    'page'?: number;
    /**
     * Number of results per page
     * @type {number}
     * @memberof EditorialImageContentDataList
     */
    'per_page'?: number;
    /**
     * Total count of all results
     * @type {number}
     * @memberof EditorialImageContentDataList
     */
    'total_count'?: number;
}

