/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EditorialAssets } from './editorial-assets';
import { EditorialCategory } from './editorial-category';
import { EditorialUpdatedContentCommercialStatus } from './editorial-updated-content-commercial-status';
import { EditorialUpdatedContentRights } from './editorial-updated-content-rights';

/**
 * Metadata about updated editorial content
 * @export
 * @interface EditorialUpdatedContent
 */
export interface EditorialUpdatedContent {
    /**
     * 
     * @type {string}
     * @memberof EditorialUpdatedContent
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialUpdatedContent
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof EditorialUpdatedContent
     */
    'aspect'?: number;
    /**
     * 
     * @type {EditorialAssets}
     * @memberof EditorialUpdatedContent
     */
    'assets'?: EditorialAssets;
    /**
     * 
     * @type {string}
     * @memberof EditorialUpdatedContent
     */
    'byline'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialUpdatedContent
     */
    'caption'?: string;
    /**
     * List of categories
     * @type {Array<EditorialCategory>}
     * @memberof EditorialUpdatedContent
     */
    'categories'?: Array<EditorialCategory>;
    /**
     * 
     * @type {EditorialUpdatedContentCommercialStatus}
     * @memberof EditorialUpdatedContent
     */
    'commercial_status'?: EditorialUpdatedContentCommercialStatus;
    /**
     * 
     * @type {string}
     * @memberof EditorialUpdatedContent
     */
    'created_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialUpdatedContent
     */
    'date_taken'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialUpdatedContent
     */
    'id': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditorialUpdatedContent
     */
    'keywords'?: Array<string>;
    /**
     * 
     * @type {EditorialUpdatedContentRights}
     * @memberof EditorialUpdatedContent
     */
    'rights'?: EditorialUpdatedContentRights;
    /**
     * 
     * @type {string}
     * @memberof EditorialUpdatedContent
     */
    'special_instructions'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialUpdatedContent
     */
    'supplier_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialUpdatedContent
     */
    'updated_time'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditorialUpdatedContent
     */
    'updates'?: Array<string>;
}

