/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EditorialAssets } from './editorial-assets';
import { EditorialCategory } from './editorial-category';

/**
 * Metadata about editorial content
 * @export
 * @interface EditorialContent
 */
export interface EditorialContent {
    /**
     * 
     * @type {string}
     * @memberof EditorialContent
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialContent
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof EditorialContent
     */
    'aspect'?: number;
    /**
     * 
     * @type {EditorialAssets}
     * @memberof EditorialContent
     */
    'assets'?: EditorialAssets;
    /**
     * 
     * @type {string}
     * @memberof EditorialContent
     */
    'byline'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialContent
     */
    'caption'?: string;
    /**
     * List of categories
     * @type {Array<EditorialCategory>}
     * @memberof EditorialContent
     */
    'categories'?: Array<EditorialCategory>;
    /**
     * 
     * @type {string}
     * @memberof EditorialContent
     */
    'date_taken'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialContent
     */
    'id': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditorialContent
     */
    'keywords'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EditorialContent
     */
    'special_instructions'?: string;
}

