/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EditorialCategory } from './editorial-category';
import { EditorialVideoAssets } from './editorial-video-assets';

/**
 * Metadata about editorial content
 * @export
 * @interface EditorialVideoContent
 */
export interface EditorialVideoContent {
    /**
     * 
     * @type {string}
     * @memberof EditorialVideoContent
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialVideoContent
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof EditorialVideoContent
     */
    'aspect'?: number;
    /**
     * 
     * @type {EditorialVideoAssets}
     * @memberof EditorialVideoContent
     */
    'assets'?: EditorialVideoAssets;
    /**
     * 
     * @type {string}
     * @memberof EditorialVideoContent
     */
    'byline'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialVideoContent
     */
    'caption'?: string;
    /**
     * List of categories
     * @type {Array<EditorialCategory>}
     * @memberof EditorialVideoContent
     */
    'categories'?: Array<EditorialCategory>;
    /**
     * 
     * @type {string}
     * @memberof EditorialVideoContent
     */
    'date_taken'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditorialVideoContent
     */
    'id': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditorialVideoContent
     */
    'keywords'?: Array<string>;
}

