/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VideoPreviewUrl } from './video-preview-url';
import { VideoSizeDetails } from './video-size-details';

/**
 * Asset information, including size and thumbnail URLs
 * @export
 * @interface EditorialVideoAssets
 */
export interface EditorialVideoAssets {
    /**
     * 
     * @type {VideoSizeDetails}
     * @memberof EditorialVideoAssets
     */
    'original'?: VideoSizeDetails;
    /**
     * 
     * @type {VideoPreviewUrl}
     * @memberof EditorialVideoAssets
     */
    'preview_mp4'?: VideoPreviewUrl;
    /**
     * 
     * @type {VideoPreviewUrl}
     * @memberof EditorialVideoAssets
     */
    'preview_webm'?: VideoPreviewUrl;
    /**
     * 
     * @type {VideoPreviewUrl}
     * @memberof EditorialVideoAssets
     */
    'thumb_jpg'?: VideoPreviewUrl;
}

