/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EditorialLivefeed } from './editorial-livefeed';

/**
 * List of editorial livefeeds
 * @export
 * @interface EditorialLivefeedList
 */
export interface EditorialLivefeedList {
    /**
     * Editorial livefeeds
     * @type {Array<EditorialLivefeed>}
     * @memberof EditorialLivefeedList
     */
    'data': Array<EditorialLivefeed>;
    /**
     * Optional error message
     * @type {string}
     * @memberof EditorialLivefeedList
     */
    'message'?: string;
    /**
     * Current page of the response
     * @type {number}
     * @memberof EditorialLivefeedList
     */
    'page'?: number;
    /**
     * Number of results per page
     * @type {number}
     * @memberof EditorialLivefeedList
     */
    'per_page'?: number;
    /**
     * Total count of all results
     * @type {number}
     * @memberof EditorialLivefeedList
     */
    'total_count': number;
}

