/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Cover image for editorial livefeed
 * @export
 * @interface EditorialCoverItem
 */
export interface EditorialCoverItem {
    /**
     * 
     * @type {number}
     * @memberof EditorialCoverItem
     */
    'height'?: number;
    /**
     * 
     * @type {string}
     * @memberof EditorialCoverItem
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof EditorialCoverItem
     */
    'url': string;
    /**
     * 
     * @type {number}
     * @memberof EditorialCoverItem
     */
    'width'?: number;
}

