/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeaturedCollection } from './featured-collection';

/**
 * List of featured collections
 * @export
 * @interface FeaturedCollectionDataList
 */
export interface FeaturedCollectionDataList {
    /**
     * Featured collections
     * @type {Array<FeaturedCollection>}
     * @memberof FeaturedCollectionDataList
     */
    'data'?: Array<FeaturedCollection>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof FeaturedCollectionDataList
     */
    'errors'?: Array<Error>;
    /**
     * Server-generated message, if any
     * @type {string}
     * @memberof FeaturedCollectionDataList
     */
    'message'?: string;
    /**
     * Current page that is returned
     * @type {number}
     * @memberof FeaturedCollectionDataList
     */
    'page'?: number;
    /**
     * Number of results per page
     * @type {number}
     * @memberof FeaturedCollectionDataList
     */
    'per_page'?: number;
    /**
     * Total count of all results across all pages
     * @type {number}
     * @memberof FeaturedCollectionDataList
     */
    'total_count'?: number;
}

