/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ImageSizeDetails } from './image-size-details';
import { Thumbnail } from './thumbnail';

/**
 * Information about the assets that are part of an image
 * @export
 * @interface ImageAssets
 */
export interface ImageAssets {
    /**
     * 
     * @type {ImageSizeDetails}
     * @memberof ImageAssets
     */
    'huge_jpg'?: ImageSizeDetails;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ImageAssets
     */
    'huge_thumb'?: Thumbnail;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ImageAssets
     */
    'large_thumb'?: Thumbnail;
    /**
     * 
     * @type {ImageSizeDetails}
     * @memberof ImageAssets
     */
    'medium_jpg'?: ImageSizeDetails;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ImageAssets
     */
    'preview'?: Thumbnail;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ImageAssets
     */
    'preview_1000'?: Thumbnail;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ImageAssets
     */
    'preview_1500'?: Thumbnail;
    /**
     * 
     * @type {ImageSizeDetails}
     * @memberof ImageAssets
     */
    'small_jpg'?: ImageSizeDetails;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ImageAssets
     */
    'small_thumb'?: Thumbnail;
    /**
     * 
     * @type {ImageSizeDetails}
     * @memberof ImageAssets
     */
    'supersize_jpg'?: ImageSizeDetails;
    /**
     * 
     * @type {ImageSizeDetails}
     * @memberof ImageAssets
     */
    'vector_eps'?: ImageSizeDetails;
}

