/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Category } from './category';
import { Contributor } from './contributor';
import { ImageAssets } from './image-assets';
import { ImageInsights } from './image-insights';
import { Model } from './model';
import { ModelRelease } from './model-release';

/**
 * Information about an image
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * Detailed description of the image
     * @type {string}
     * @memberof Image
     */
    'description'?: string;
    /**
     * Date that the image was added by the contributor
     * @type {string}
     * @memberof Image
     */
    'added_date'?: string;
    /**
     * Affiliate referral link; appears only for registered affiliate partners
     * @type {string}
     * @memberof Image
     */
    'affiliate_url'?: string;
    /**
     * Aspect ratio of the image in decimal format, such as 0.6667
     * @type {number}
     * @memberof Image
     */
    'aspect'?: number;
    /**
     * 
     * @type {ImageAssets}
     * @memberof Image
     */
    'assets'?: ImageAssets;
    /**
     * Categories that this image is a part of
     * @type {Array<Category>}
     * @memberof Image
     */
    'categories'?: Array<Category>;
    /**
     * 
     * @type {Contributor}
     * @memberof Image
     */
    'contributor': Contributor;
    /**
     * Indicates whether there are model releases for the image
     * @type {boolean}
     * @memberof Image
     */
    'has_model_release'?: boolean;
    /**
     * Indicates whether there are property releases for the image
     * @type {boolean}
     * @memberof Image
     */
    'has_property_release'?: boolean;
    /**
     * Image ID
     * @type {string}
     * @memberof Image
     */
    'id': string;
    /**
     * Type of image
     * @type {string}
     * @memberof Image
     */
    'image_type'?: string;
    /**
     * 
     * @type {ImageInsights}
     * @memberof Image
     */
    'insights'?: ImageInsights;
    /**
     * Whether or not this image contains adult content
     * @type {boolean}
     * @memberof Image
     */
    'is_adult'?: boolean;
    /**
     * Whether or not this image is editorial content
     * @type {boolean}
     * @memberof Image
     */
    'is_editorial'?: boolean;
    /**
     * Whether or not this image is an illustration
     * @type {boolean}
     * @memberof Image
     */
    'is_illustration'?: boolean;
    /**
     * Keywords associated with the content of this image
     * @type {Array<string>}
     * @memberof Image
     */
    'keywords'?: Array<string>;
    /**
     * Media type of this image, should always be \"image\"
     * @type {string}
     * @memberof Image
     */
    'media_type': string;
    /**
     * List of model releases
     * @type {Array<ModelRelease>}
     * @memberof Image
     */
    'model_releases'?: Array<ModelRelease>;
    /**
     * List of models
     * @type {Array<Model>}
     * @memberof Image
     */
    'models'?: Array<Model>;
    /**
     * List of all releases of this image
     * @type {Array<string>}
     * @memberof Image
     */
    'releases'?: Array<string>;
    /**
     * Link to image information page; included only for certain accounts
     * @type {string}
     * @memberof Image
     */
    'url'?: string;
}

