/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InsightsLabelPerformanceInner } from './insights-label-performance-inner';

/**
 * AI-powered insights about an asset, based on the specified audience and objective
 * @export
 * @interface Insights
 */
export interface Insights {
    /**
     * How effective the AI thinks an asset in the category is for the specified audience and objective, expressed as a percentile compared to other images
     * @type {Array<InsightsLabelPerformanceInner>}
     * @memberof Insights
     */
    'label_performance': Array<InsightsLabelPerformanceInner>;
}

