/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Preview } from './preview';

/**
 * Information about an musical instrument
 * @export
 * @interface Instrument
 */
export interface Instrument {
    /**
     * List of tags
     * @type {Array<string>}
     * @memberof Instrument
     */
    'tags'?: Array<string>;
    /**
     * The id of the instrument
     * @type {string}
     * @memberof Instrument
     */
    'id'?: string;
    /**
     * Name of the instrument
     * @type {string}
     * @memberof Instrument
     */
    'name'?: string;
    /**
     * Preview of the instrument
     * @type {Array<Preview>}
     * @memberof Instrument
     */
    'previews'?: Array<Preview>;
}

