/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ISOCountryCodeOneOf } from './isocountry-code-one-of';
import { ISOCountryCodeOneOf1 } from './isocountry-code-one-of1';

/**
 * @type ISOCountryCode
 * A valid ISO 3166-1 Alpha-2 or ISO 3166-1 Alpha-3 code.
 * @export
 */
export type ISOCountryCode = ISOCountryCodeOneOf | ISOCountryCodeOneOf1;


