/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * List of keywords
 * @export
 * @interface KeywordDataList
 */
export interface KeywordDataList {
    /**
     * Keywords
     * @type {Array<string>}
     * @memberof KeywordDataList
     */
    'data'?: Array<string>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof KeywordDataList
     */
    'errors'?: Array<Error>;
    /**
     * Server-generated message, if any
     * @type {string}
     * @memberof KeywordDataList
     */
    'message'?: string;
}

