/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LicenseSFXResult } from './license-sfxresult';

/**
 * List of information about licensed sound effects
 * @export
 * @interface LicenseSFXResultDataList
 */
export interface LicenseSFXResultDataList {
    /**
     * Sound effects license results
     * @type {Array<LicenseSFXResult>}
     * @memberof LicenseSFXResultDataList
     */
    'data'?: Array<LicenseSFXResult>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof LicenseSFXResultDataList
     */
    'errors'?: Array<Error>;
    /**
     * Server-generated message, if any
     * @type {string}
     * @memberof LicenseSFXResultDataList
     */
    'message'?: string;
}

