/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Url } from './url';

/**
 * The response to a licensing request for an sound effects
 * @export
 * @interface LicenseSFXResult
 */
export interface LicenseSFXResult {
    /**
     * Number of credits that this licensing event used
     * @type {number}
     * @memberof LicenseSFXResult
     */
    'allotment_charge'?: number;
    /**
     * 
     * @type {Url}
     * @memberof LicenseSFXResult
     */
    'download'?: Url;
    /**
     * Error message, appears only if there was an error
     * @type {string}
     * @memberof LicenseSFXResult
     */
    'error'?: string;
    /**
     * ID of the license event
     * @type {string}
     * @memberof LicenseSFXResult
     */
    'license_id'?: string;
    /**
     * Sound effects ID that was licensed
     * @type {string}
     * @memberof LicenseSFXResult
     */
    'sfx_id': string;
}

