/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Cookie } from './cookie';

/**
 * Data required to license an image
 * @export
 * @interface LicenseImageVector
 */
export interface LicenseImageVector {
    /**
     * 
     * @type {Cookie}
     * @memberof LicenseImageVector
     */
    'auth_cookie'?: Cookie;
    /**
     * Set to true to acknowledge the editorial agreement
     * @type {boolean}
     * @memberof LicenseImageVector
     */
    'editorial_acknowledgement'?: boolean;
    /**
     * (Deprecated) Image format to download
     * @type {string}
     * @memberof LicenseImageVector
     */
    'format'?: LicenseImageVectorFormatEnum;
    /**
     * Image ID
     * @type {string}
     * @memberof LicenseImageVector
     */
    'image_id': string;
    /**
     * Additional information for license requests for enterprise accounts and API subscriptions, 4 fields maximum; which fields are required is set by the account holder
     * @type {object}
     * @memberof LicenseImageVector
     */
    'metadata'?: object;
    /**
     * For revenue-sharing transactions, the final cost to the end customer as a floating-point number in the transaction currency, such as 12.34
     * @type {number}
     * @memberof LicenseImageVector
     */
    'price'?: number;
    /**
     * ID of the search that led to this licensing transaction
     * @type {string}
     * @memberof LicenseImageVector
     */
    'search_id'?: string;
    /**
     * (Deprecated)
     * @type {boolean}
     * @memberof LicenseImageVector
     * @deprecated
     */
    'show_modal'?: boolean;
    /**
     * Image size to download
     * @type {string}
     * @memberof LicenseImageVector
     */
    'size'?: LicenseImageVectorSizeEnum;
    /**
     * ID of the subscription to use for the download.
     * @type {string}
     * @memberof LicenseImageVector
     */
    'subscription_id'?: string;
    /**
     * (Deprecated)
     * @type {string}
     * @memberof LicenseImageVector
     * @deprecated
     */
    'verification_code'?: string;
}

type LicenseImageVectorFormatEnum = 'eps'
type LicenseImageVectorSizeEnum = 'vector'


