/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An audio track in a licensing request
 * @export
 * @interface LicenseAudio
 */
export interface LicenseAudio {
    /**
     * ID of the track being licensed
     * @type {string}
     * @memberof LicenseAudio
     */
    'audio_id': string;
    /**
     * Type of license
     * @type {string}
     * @memberof LicenseAudio
     */
    'license'?: LicenseAudioLicenseEnum;
    /**
     * ID of the search that led to this licensing event
     * @type {string}
     * @memberof LicenseAudio
     */
    'search_id'?: string;
}

type LicenseAudioLicenseEnum = 'audio_platform' | 'premier_music_basic' | 'premier_music_extended' | 'premier_music_pro' | 'premier_music_comp' | 'asset_all_music'


