/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LicenseSFX
 */
export interface LicenseSFX {
    /**
     * 
     * @type {string}
     * @memberof LicenseSFX
     */
    'audio_layout'?: LicenseSFXAudioLayoutEnum;
    /**
     * 
     * @type {string}
     * @memberof LicenseSFX
     */
    'format'?: LicenseSFXFormatEnum;
    /**
     * ID of the search that led to this licensing event
     * @type {string}
     * @memberof LicenseSFX
     */
    'search_id'?: string;
    /**
     * ID of the sounds effect being licensed
     * @type {string}
     * @memberof LicenseSFX
     */
    'sfx_id': string;
    /**
     * ID of the subscription to use for the download.
     * @type {string}
     * @memberof LicenseSFX
     */
    'subscription_id': string;
}

type LicenseSFXAudioLayoutEnum = 'ambisonic' | '5.1' | 'stereo'
type LicenseSFXFormatEnum = 'wav' | 'mp3'


