/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ISOCountryCode } from './isocountry-code';
import { LicenseEditorialVideoContent } from './license-editorial-video-content';

/**
 * License editorial video content request
 * @export
 * @interface LicenseEditorialVideoContentRequest
 */
export interface LicenseEditorialVideoContentRequest {
    /**
     * 
     * @type {ISOCountryCode}
     * @memberof LicenseEditorialVideoContentRequest
     */
    'country': ISOCountryCode;
    /**
     * Editorial content to license
     * @type {Array<LicenseEditorialVideoContent>}
     * @memberof LicenseEditorialVideoContentRequest
     */
    'editorial': Array<LicenseEditorialVideoContent>;
}

