/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about a human model or property that appears in media; used to search for assets that this model is in
 * @export
 * @interface Model
 */
export interface Model {
    /**
     * ID of the model
     * @type {string}
     * @memberof Model
     */
    'id': string;
}

