/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Access token response to client apps
 * @export
 * @interface OauthAccessTokenResponse
 */
export interface OauthAccessTokenResponse {
    /**
     * Access token that can be used for future requests
     * @type {string}
     * @memberof OauthAccessTokenResponse
     */
    'access_token': string;
    /**
     * Number of seconds before token expires, only present for expiring tokens
     * @type {number}
     * @memberof OauthAccessTokenResponse
     */
    'expires_in'?: number;
    /**
     * A refresh token that can be used to renew the access_token when it expires, only present for expiring tokens
     * @type {string}
     * @memberof OauthAccessTokenResponse
     */
    'refresh_token'?: string;
    /**
     * Type of token
     * @type {string}
     * @memberof OauthAccessTokenResponse
     */
    'token_type': string;
    /**
     * Metadata about the access_token, only present for expiring tokens
     * @type {string}
     * @memberof OauthAccessTokenResponse
     */
    'user_token'?: string;
}

