/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OauthGetUserAccessTokenRequest
 */
export interface OauthGetUserAccessTokenRequest {
    /**
     * Client ID (Consumer Key) of your application
     * @type {string}
     * @memberof OauthGetUserAccessTokenRequest
     */
    'client_id': string;
    /**
     * Client Secret (Consumer Secret) of your application
     * @type {string}
     * @memberof OauthGetUserAccessTokenRequest
     */
    'client_secret'?: string;
    /**
     * Response code from the /oauth/authorize flow; required if grant_type=authorization_code
     * @type {string}
     * @memberof OauthGetUserAccessTokenRequest
     */
    'code'?: string;
    /**
     * Whether or not the token expires, expiring tokens come with a refresh_token to renew the access_token
     * @type {boolean}
     * @memberof OauthGetUserAccessTokenRequest
     */
    'expires'?: boolean;
    /**
     * Grant type: authorization_code generates user tokens, client_credentials generates short-lived client grants
     * @type {string}
     * @memberof OauthGetUserAccessTokenRequest
     */
    'grant_type': OauthGetUserAccessTokenRequestGrantTypeEnum;
    /**
     * User type to be authorized (usually \'customer\')
     * @type {string}
     * @memberof OauthGetUserAccessTokenRequest
     */
    'realm'?: OauthGetUserAccessTokenRequestRealmEnum;
    /**
     * Pass this along with grant_type=refresh_token to get a fresh access token
     * @type {string}
     * @memberof OauthGetUserAccessTokenRequest
     */
    'refresh_token'?: string;
}

type OauthGetUserAccessTokenRequestGrantTypeEnum = 'authorization_code' | 'client_credentials' | 'refresh_token'
type OauthGetUserAccessTokenRequestRealmEnum = 'customer' | 'contributor'


