/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Preview information
 * @export
 * @interface Preview
 */
export interface Preview {
    /**
     * Content type of the preview, currently audio/mp3
     * @type {string}
     * @memberof Preview
     */
    'content_type'?: PreviewContentTypeEnum;
    /**
     * Url of the instrument\'s preview file
     * @type {string}
     * @memberof Preview
     */
    'url'?: string;
}

type PreviewContentTypeEnum = 'audio/mp3'


