/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Price
 * @export
 * @interface Price
 */
export interface Price {
    /**
     * Floating-point amount of the calculated rev-share price in the currency local_currency
     * @type {number}
     * @memberof Price
     */
    'local_amount'?: number;
    /**
     * Currency of the rev-share price that was calculated
     * @type {string}
     * @memberof Price
     */
    'local_currency'?: string;
}

