/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Recommendation } from './recommendation';

/**
 * List of recommended images
 * @export
 * @interface RecommendationDataList
 */
export interface RecommendationDataList {
    /**
     * Recommended images
     * @type {Array<Recommendation>}
     * @memberof RecommendationDataList
     */
    'data'?: Array<Recommendation>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof RecommendationDataList
     */
    'errors'?: Array<Error>;
    /**
     * Server-generated message, if any
     * @type {string}
     * @memberof RecommendationDataList
     */
    'message'?: string;
    /**
     * Current page that is returned
     * @type {number}
     * @memberof RecommendationDataList
     */
    'page'?: number;
    /**
     * Number of results per page
     * @type {number}
     * @memberof RecommendationDataList
     */
    'per_page'?: number;
    /**
     * Total count of all results across all pages
     * @type {number}
     * @memberof RecommendationDataList
     */
    'total_count'?: number;
}

