/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Cookie } from './cookie';

/**
 * Data required to redownload a video
 * @export
 * @interface RedownloadVideo
 */
export interface RedownloadVideo {
    /**
     * 
     * @type {Cookie}
     * @memberof RedownloadVideo
     */
    'auth_cookie'?: Cookie;
    /**
     * (Deprecated)
     * @type {boolean}
     * @memberof RedownloadVideo
     * @deprecated
     */
    'show_modal'?: boolean;
    /**
     * Size of the video
     * @type {string}
     * @memberof RedownloadVideo
     */
    'size'?: RedownloadVideoSizeEnum;
    /**
     * (Deprecated)
     * @type {string}
     * @memberof RedownloadVideo
     * @deprecated
     */
    'verification_code'?: string;
}

type RedownloadVideoSizeEnum = 'web' | 'sd' | 'hd' | '4k'


