/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Cookie } from './cookie';

/**
 * Data required to redownload an image
 * @export
 * @interface RedownloadImage
 */
export interface RedownloadImage {
    /**
     * 
     * @type {Cookie}
     * @memberof RedownloadImage
     */
    'auth_cookie'?: Cookie;
    /**
     * (Deprecated)
     * @type {boolean}
     * @memberof RedownloadImage
     * @deprecated
     */
    'show_modal'?: boolean;
    /**
     * Size of the image
     * @type {string}
     * @memberof RedownloadImage
     */
    'size'?: RedownloadImageSizeEnum;
    /**
     * (Deprecated)
     * @type {string}
     * @memberof RedownloadImage
     * @deprecated
     */
    'verification_code'?: string;
}

type RedownloadImageSizeEnum = 'small' | 'medium' | 'huge' | 'supersize' | 'vector'


