/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * @type SearchImageRegion
 * Raise or lower search result rankings based on the result\'s relevance to a specified region; you can provide a country code or an IP address from which the API infers a country
 * @export
 */
export type SearchImageRegion = string;


