/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Sound effect license URL object
 * @export
 * @interface SfxUrl
 */
export interface SfxUrl {
    /**
     * URL that can be used to download the unwatermarked, licensed asset
     * @type {string}
     * @memberof SfxUrl
     */
    'url': string;
}

