/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SFXAssetDetails } from './sfxasset-details';

/**
 * Files that are available as part of an sound effect asset
 * @export
 * @interface SFXAssets
 */
export interface SFXAssets {
    /**
     * 
     * @type {SFXAssetDetails}
     * @memberof SFXAssets
     */
    'preview_mp3'?: SFXAssetDetails;
    /**
     * 
     * @type {SFXAssetDetails}
     * @memberof SFXAssets
     */
    'waveform'?: SFXAssetDetails;
}

