/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about a file that is part of an sound effect asset
 * @export
 * @interface SFXAssetDetails
 */
export interface SFXAssetDetails {
    /**
     * File size of the sound effect
     * @type {number}
     * @memberof SFXAssetDetails
     */
    'file_size'?: number;
    /**
     * URL the sound effect is available at
     * @type {string}
     * @memberof SFXAssetDetails
     */
    'url'?: string;
}

