/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Subscription } from './subscription';

/**
 * List of subscriptions
 * @export
 * @interface SubscriptionDataList
 */
export interface SubscriptionDataList {
    /**
     * Subscriptions retrieved from this user
     * @type {Array<Subscription>}
     * @memberof SubscriptionDataList
     */
    'data'?: Array<Subscription>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof SubscriptionDataList
     */
    'errors'?: Array<Error>;
    /**
     * Optional error message
     * @type {string}
     * @memberof SubscriptionDataList
     */
    'message'?: string;
    /**
     * Current page that is being queried
     * @type {number}
     * @memberof SubscriptionDataList
     */
    'page'?: number;
    /**
     * Amount of subscriptions to show per page
     * @type {number}
     * @memberof SubscriptionDataList
     */
    'per_page'?: number;
    /**
     * Total number of subscriptions for this user
     * @type {number}
     * @memberof SubscriptionDataList
     */
    'total_count'?: number;
}

