/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Allotment } from './allotment';
import { LicenseFormat } from './license-format';
import { Price } from './price';

/**
 * Subscription information
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * Description of the subscription
     * @type {string}
     * @memberof Subscription
     */
    'description'?: string;
    /**
     * 
     * @type {Allotment}
     * @memberof Subscription
     */
    'allotment'?: Allotment;
    /**
     * Identifier for the type of assets associated with this subscription (images, videos, audio, editorial)
     * @type {string}
     * @memberof Subscription
     */
    'asset_type'?: string;
    /**
     * Date the subscription ends
     * @type {string}
     * @memberof Subscription
     */
    'expiration_time'?: string;
    /**
     * List of formats that are licensable for the subscription
     * @type {Array<LicenseFormat>}
     * @memberof Subscription
     */
    'formats'?: Array<LicenseFormat>;
    /**
     * Unique internal identifier for the subscription
     * @type {string}
     * @memberof Subscription
     */
    'id': string;
    /**
     * Internal identifier for the type of subscription
     * @type {string}
     * @memberof Subscription
     */
    'license'?: string;
    /**
     * Subscription metadata; different for each customer
     * @type {object}
     * @memberof Subscription
     */
    'metadata'?: object;
    /**
     * 
     * @type {Price}
     * @memberof Subscription
     */
    'price_per_download'?: Price;
}

