/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about a piece of updated media
 * @export
 * @interface UpdatedMedia
 */
export interface UpdatedMedia {
    /**
     * ID of the media
     * @type {string}
     * @memberof UpdatedMedia
     */
    'id': string;
    /**
     * Date that the media was updated
     * @type {string}
     * @memberof UpdatedMedia
     */
    'updated_time': string;
    /**
     * Types of updates that were made to the piece of media
     * @type {Array<string>}
     * @memberof UpdatedMedia
     */
    'updates': Array<string>;
}

