/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UpdatedMedia } from './updated-media';

/**
 * List of updated media
 * @export
 * @interface UpdatedMediaDataList
 */
export interface UpdatedMediaDataList {
    /**
     * Updated media items
     * @type {Array<UpdatedMedia>}
     * @memberof UpdatedMediaDataList
     */
    'data'?: Array<UpdatedMedia>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof UpdatedMediaDataList
     */
    'errors'?: Array<Error>;
    /**
     * Server-generated message, if any
     * @type {string}
     * @memberof UpdatedMediaDataList
     */
    'message'?: string;
    /**
     * Current page that is returned
     * @type {number}
     * @memberof UpdatedMediaDataList
     */
    'page'?: number;
    /**
     * Number of results per page
     * @type {number}
     * @memberof UpdatedMediaDataList
     */
    'per_page'?: number;
    /**
     * Total count of all results across all pages
     * @type {number}
     * @memberof UpdatedMediaDataList
     */
    'total_count'?: number;
}

