/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * User details
 * @export
 * @interface UserDetails
 */
export interface UserDetails {
    /**
     * Unique internal identifier of the user, as a contributor
     * @type {string}
     * @memberof UserDetails
     */
    'contributor_id'?: string;
    /**
     * Unique internal identifier of the user, as a purchaser
     * @type {string}
     * @memberof UserDetails
     */
    'customer_id'?: string;
    /**
     * Email address of the user
     * @type {string}
     * @memberof UserDetails
     */
    'email'?: string;
    /**
     * First name of the user
     * @type {string}
     * @memberof UserDetails
     */
    'first_name'?: string;
    /**
     * Full name including first, middle, and last name of the user
     * @type {string}
     * @memberof UserDetails
     */
    'full_name'?: string;
    /**
     * Unique internal identifier for the user, not tied to contributor or purchasing customer
     * @type {string}
     * @memberof UserDetails
     */
    'id'?: string;
    /**
     * True if the user has access to the Premier collection, false otherwise
     * @type {boolean}
     * @memberof UserDetails
     */
    'is_premier'?: boolean;
    /**
     * True if the user has access to the Premier collection and also has child users
     * @type {boolean}
     * @memberof UserDetails
     */
    'is_premier_parent'?: boolean;
    /**
     * Main language of the user account
     * @type {string}
     * @memberof UserDetails
     */
    'language'?: string;
    /**
     * Last name of the user
     * @type {string}
     * @memberof UserDetails
     */
    'last_name'?: string;
    /**
     * True if the user has an enterprise license, false otherwise
     * @type {boolean}
     * @memberof UserDetails
     */
    'only_enhanced_license'?: boolean;
    /**
     * True if the user has access to sensitive use only, false otherwise
     * @type {boolean}
     * @memberof UserDetails
     */
    'only_sensitive_use'?: boolean;
    /**
     * Unique internal identifier for the user\'s organization, specific to Premier users
     * @type {string}
     * @memberof UserDetails
     */
    'organization_id'?: string;
    /**
     * List of permissions allowed through the Premier client
     * @type {Array<string>}
     * @memberof UserDetails
     */
    'premier_permissions'?: Array<string>;
    /**
     * User name associated to the user
     * @type {string}
     * @memberof UserDetails
     */
    'username'?: string;
}

