/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Url } from './url';
import { Urls } from './urls';
import { VideoSizeDetails } from './video-size-details';

/**
 * Video asset information
 * @export
 * @interface VideoAssets
 */
export interface VideoAssets {
    /**
     * 
     * @type {VideoSizeDetails}
     * @memberof VideoAssets
     */
    '4k'?: VideoSizeDetails;
    /**
     * 
     * @type {VideoSizeDetails}
     * @memberof VideoAssets
     */
    'hd'?: VideoSizeDetails;
    /**
     * 
     * @type {Url}
     * @memberof VideoAssets
     */
    'preview_jpg'?: Url;
    /**
     * 
     * @type {Url}
     * @memberof VideoAssets
     */
    'preview_mp4'?: Url;
    /**
     * 
     * @type {Url}
     * @memberof VideoAssets
     */
    'preview_webm'?: Url;
    /**
     * 
     * @type {VideoSizeDetails}
     * @memberof VideoAssets
     */
    'sd'?: VideoSizeDetails;
    /**
     * 
     * @type {Url}
     * @memberof VideoAssets
     */
    'thumb_jpg'?: Url;
    /**
     * 
     * @type {Urls}
     * @memberof VideoAssets
     */
    'thumb_jpgs'?: Urls;
    /**
     * 
     * @type {Url}
     * @memberof VideoAssets
     */
    'thumb_mp4'?: Url;
    /**
     * 
     * @type {Url}
     * @memberof VideoAssets
     */
    'thumb_webm'?: Url;
    /**
     * 
     * @type {VideoSizeDetails}
     * @memberof VideoAssets
     */
    'web'?: VideoSizeDetails;
}

