/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Video preview information
 * @export
 * @interface VideoPreviewUrl
 */
export interface VideoPreviewUrl {
    /**
     * Direct URL to the image
     * @type {string}
     * @memberof VideoPreviewUrl
     */
    'url': string;
}

