/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CollectionItem } from './collection-item';

/**
 * List of items in a collection
 * @export
 * @interface VideoCollectionItemDataList
 */
export interface VideoCollectionItemDataList {
    /**
     * Assets in the collection
     * @type {Array<CollectionItem>}
     * @memberof VideoCollectionItemDataList
     */
    'data'?: Array<CollectionItem>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof VideoCollectionItemDataList
     */
    'errors'?: Array<Error>;
    /**
     * Server-generated message, if any
     * @type {string}
     * @memberof VideoCollectionItemDataList
     */
    'message'?: string;
    /**
     * The current page of results
     * @type {number}
     * @memberof VideoCollectionItemDataList
     */
    'page'?: number;
    /**
     * The number of results per page
     * @type {number}
     * @memberof VideoCollectionItemDataList
     */
    'per_page'?: number;
    /**
     * The total number of results across all pages
     * @type {number}
     * @memberof VideoCollectionItemDataList
     */
    'total_count'?: number;
}

