/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Category } from './category';
import { Contributor } from './contributor';
import { Model } from './model';
import { VideoAssets } from './video-assets';

/**
 * Information about a video
 * @export
 * @interface Video
 */
export interface Video {
    /**
     * Description of this video
     * @type {string}
     * @memberof Video
     */
    'description'?: string;
    /**
     * Date this video was added to the Shutterstock library
     * @type {string}
     * @memberof Video
     */
    'added_date'?: string;
    /**
     * Affiliate referral link; appears only for registered affiliate partners
     * @type {string}
     * @memberof Video
     */
    'affiliate_url'?: string;
    /**
     * Aspect ratio of this video in decimal format, such as 0.6667
     * @type {number}
     * @memberof Video
     */
    'aspect'?: number;
    /**
     * Aspect ratio of the video as a ratio, such as 16:9
     * @type {string}
     * @memberof Video
     */
    'aspect_ratio'?: string;
    /**
     * 
     * @type {VideoAssets}
     * @memberof Video
     */
    'assets'?: VideoAssets;
    /**
     * List of categories
     * @type {Array<Category>}
     * @memberof Video
     */
    'categories'?: Array<Category>;
    /**
     * 
     * @type {Contributor}
     * @memberof Video
     */
    'contributor': Contributor;
    /**
     * Duration of this video, in seconds
     * @type {number}
     * @memberof Video
     */
    'duration'?: number;
    /**
     * Whether or not this video has been released for use by the model appearing in it
     * @type {boolean}
     * @memberof Video
     */
    'has_model_release'?: boolean;
    /**
     * Whether or not this video has received a release to show the landmark or property appearing in it
     * @type {boolean}
     * @memberof Video
     */
    'has_property_release'?: boolean;
    /**
     * ID of the video
     * @type {string}
     * @memberof Video
     */
    'id': string;
    /**
     * Whether or not this video contains adult content
     * @type {boolean}
     * @memberof Video
     */
    'is_adult'?: boolean;
    /**
     * Whether or not this video is editorial content
     * @type {boolean}
     * @memberof Video
     */
    'is_editorial'?: boolean;
    /**
     * Keywords associated with the content of this video
     * @type {Array<string>}
     * @memberof Video
     */
    'keywords'?: Array<string>;
    /**
     * Media type of this video, should always be \"video\"
     * @type {string}
     * @memberof Video
     */
    'media_type': string;
    /**
     * List of models in this video
     * @type {Array<Model>}
     * @memberof Video
     */
    'models'?: Array<Model>;
    /**
     * Link to video information page; included only for certain accounts
     * @type {string}
     * @memberof Video
     */
    'url'?: string;
}

