/*
Shutterstock API Explorer

The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.

The version of the OpenAPI document: 1.1.32


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Video } from './video';

/**
 * List of videos
 * @export
 * @interface VideoDataList
 */
export interface VideoDataList {
    /**
     * Videos
     * @type {Array<Video>}
     * @memberof VideoDataList
     */
    'data'?: Array<Video>;
    /**
     * Error list; appears only if there was an error
     * @type {Array<Error>}
     * @memberof VideoDataList
     */
    'errors'?: Array<Error>;
    /**
     * Server-generated message, if any
     * @type {string}
     * @memberof VideoDataList
     */
    'message'?: string;
    /**
     * Current page that is returned
     * @type {number}
     * @memberof VideoDataList
     */
    'page'?: number;
    /**
     * Number of results per page
     * @type {number}
     * @memberof VideoDataList
     */
    'per_page'?: number;
    /**
     * Total count of all results across all pages
     * @type {number}
     * @memberof VideoDataList
     */
    'total_count'?: number;
}

